project:
  type: website
  render:
    - "*.ipynb"

format:
  html:
    toc: true
    toc-depth: 5
    css: styles.css
    page-layout: full
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: false
    monofont: D2Coding
    language:
      crossref-tbl-title: "표"

website:
  title: "Frontend Book"
  site-url: https://frontendbook.madebykim.kr/
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - section: "Node.js"
        contents:
        - "npm_basic.ipynb"
        - "package.json.ipynb"
        - "node.ipynb"
        - "module.ipynb"
      - section: "자바스크립트"
        contents:
        - "js_type.ipynb"
      - section: "타입스크립트"
        contents:
        - "tsconfig.ipynb"
        - "tsc.ipynb"
      - section: "타입스크립트 패키지"
        contents:
        - "ts_packages.ipynb"
        - "tsc_watch.ipynb"
      - section: "HTTP Server"
        contents:
        - "http.ipynb"
